package br.com.gestaocontas.telas;

import br.com.gestaocontas.dal.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author caio
 */
public class TelaLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        status_bd();
    }

    // MÉTODO PARA TESTAR STATUS DE CONEXÃO COM BANCO DE DADOS AO INICIAR PROGRAMA
    private void status_bd() {
        Connection conexao = null;
        try {
            conexao = Conexao.conectar();
            if (conexao != null) {
                lblStatusBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestaocontas/icones/bd_ok_64px.png")));
            }
        } catch (Exception e) {
            lblStatusBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestaocontas/icones/bd_erro_64px.png")));
            JOptionPane.showMessageDialog(null, "Erro: Conexão com Banco de Dados:\n" + e.getMessage());
        } finally {
            try {
                if (conexao != null && !conexao.isClosed()) {
                    conexao.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao fechar conexão:\n" + ex.getMessage());
            }
        }
    }

    private void telaSobre() {
        TelaSobreSistema sobre = new TelaSobreSistema();
        sobre.setVisible(true);
    }

// MÉTODO PARA VALIDAÇÃO DE USUÁRIO E ACESSO À TELA PRINCIPAL
    private void logar() {
        String sqlLogin = "SELECT id_usuario, nome_usuario FROM tb_usuarios WHERE login_usuario = ? AND senha_usuario = ?";
        String sqlLogAcesso = "INSERT INTO tb_log_acessos (id_usuario, operacao_log) VALUES (?, 'entrou')";

        // VALIDAÇÃO DE CAMPOS OBRIGATÓRIOS
        if (txtUsuario.getText().isEmpty() || txtSenha.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Preencha usuário e senha!");
            return;
        }

        try (Connection conexao = Conexao.conectar()) {

            conexao.setAutoCommit(false);

            try (PreparedStatement pstLogin = conexao.prepareStatement(sqlLogin)) {
                pstLogin.setString(1, txtUsuario.getText());
                pstLogin.setString(2, new String(txtSenha.getPassword()));

                try (ResultSet rs = pstLogin.executeQuery()) {

                    if (!rs.next()) {
                        JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválido(s)!");
                        return;
                    }

                    int idUsuario = rs.getInt("id_usuario");
                    String nomeUsuario = rs.getString("nome_usuario");

                    // REGISTRA LOG
                    try (PreparedStatement pstLog = conexao.prepareStatement(sqlLogAcesso)) {
                        pstLog.setInt(1, idUsuario);

                        int acesso = pstLog.executeUpdate();

                        // SÓ CONTINUA SE O LOG FOI INSERIDO
                        if (acesso > 0) {
                            conexao.commit();

                            TelaMenuPrincipal principal = new TelaMenuPrincipal();
                            TelaMenuPrincipal.lblUsuarioLogado.setText(String.valueOf(idUsuario));
                            TelaMenuPrincipal.lblUsuario.setText(nomeUsuario);
                            principal.setVisible(true);
                            this.dispose();

                        } else {
                            conexao.rollback();
                            JOptionPane.showMessageDialog(null, "Falha ao registrar log de acesso!");
                        }
                    }
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao logar: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundo = new javax.swing.JPanel();
        txtSenha = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblStatusBD = new javax.swing.JLabel();
        lblGestaoContas = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão Contas 1.0 - Login");

        panelFundo.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuario.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblUsuario.setText("Usuário");

        lblSenha.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblSenha.setText("Senha");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestaocontas/icones/logo_64px.png"))); // NOI18N

        btnLogin.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblStatusBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestaocontas/icones/bd_erro_64px.png"))); // NOI18N

        lblGestaoContas.setFont(new java.awt.Font("Fira Sans", 1, 20)); // NOI18N
        lblGestaoContas.setText("Gestão de Contas 1.0");

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestaocontas/icones/info_48px.png"))); // NOI18N
        btnInfo.setToolTipText("Informações sobre o Software");
        btnInfo.setBorder(null);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFundoLayout = new javax.swing.GroupLayout(panelFundo);
        panelFundo.setLayout(panelFundoLayout);
        panelFundoLayout.setHorizontalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addComponent(lblGestaoContas)
                        .addGap(18, 18, 18)
                        .addComponent(lblLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInfo))
                    .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                            .addComponent(lblStatusBD)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                            .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblUsuario)
                                .addComponent(lblSenha))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsuario)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(80, 80, 80))
        );
        panelFundoLayout.setVerticalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                                .addComponent(lblGestaoContas)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                                .addComponent(btnInfo)
                                .addGap(18, 18, 18)))))
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusBD)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        telaSobre();
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblGestaoContas;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblStatusBD;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
